### ISSUE TITLE
Running in Development 

### ISSUE THREAD

**Issue by lucianocosta** [ledermann/docker-rails#1033]
Not sure it's an issue. I don't have Rails installed locally and I'm facing this error when I change Gemfile and run `docker-compose run app bundle install`

> There was an error while trying to write to `/usr/local/bundle/config`. It is likely that you need to grant write permissions for that path.

What's the proper way to deal with this and use in dev mode?

**Comment by cesc1989** [comment]
Hi @lucianocosta to me it looks you're using the `bundler` installed in the OS by default (which need sudo permission to be executed) rather than one in your personal folder (`/home/lucianocosta`, `/Users/lucionocosta`).

You should install Ruby and bundler using RVM or rbenv to solve it.

**Comment by ledermann** [comment]
Sorry, this repo is intended for production use only. For developing you need Ruby and stuff to be locally installed.
