### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by PabloC** [ledermann/docker-rails#121]
In docker, the idea is to mantain more or less the same dockerfiles (or docker-compose) between development and production enviroments.  In the case of development, what's your recommendation?

For example, a proper .dev with RAILS_ENV=production, eliminate NGINX (Puma or Unicorn is enough). What about logging?

Thanks for sharing your work!

**Comment by ledermann** [comment]
Currently, I'm using Docker mainly in production environment, not development. Of course, using for development should be possible with tweaking some ENV settings.
