### ISSUE TITLE
what/where is URL to access app locally?

### ISSUE THREAD

**Issue by jpwynn** [ledermann/docker-rails#2068]
```
git clone https://github.com/ledermann/docker-rails.git
cd docker-rails
docker-compose build
docker-compose up
```

Um, out of the box, what is the URL... e.g., what/where is DOCKER_HOST?

On  Mac, neither 127.0.0.1:3000 nor  localhost:3000 do not work.

When running Docker-compose up, it does show `Listening on http://0.0.0.0:3000` but I do not see what DOCKER_HOST is expected to access locally via browser.

**Comment by jpwynn** [comment]
Ah, found it, one has to run `docker ps -a` to get the IP/PORT for the _app. 

Not sure why it's not the usual `localhost:3000` instead of `http://0.0.0.0:59848/` but it works.

**Comment by ledermann** [comment]
Ok, seems to be solved.

**Comment by iamrahulroy** [comment]
@ledermann ~it didn't work for me.~

It'll be nice to have the instructions in the readme. 

Nevermind! I had updated the settings to customize the port, which I reverted and it worked. But it'll be nice to have this documented. @jpwynn would you like to send a PR or shall I send one?
