### ISSUE TITLE
How run Rspec (and scaffolding)

### ISSUE THREAD

**Issue by jpwynn** [ledermann/docker-rails#2069]
This cool a multi-stage Dockerize Rails app you have created. But after doing a quick smoke-test `docker build .` then `docker-compose up` browsing the app, then ^C to quit, I am now trying to get past some of the magic obscuring the most basic workflows.

It's probably my lack of experience with multi-stage builds, but anything rspec-related does not seem accessible the usual way:

How does one invoke rspec locally, and, invoke scaffolding to create rspec tests instead of /app/test?

```
docker-compose run --rm app rspec
```
gives:
```
Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "rspec": executable file not found in $PATH: unknown
ERROR: 1
```
or 

```
docker-compose run --rm app rails g scaffold Foo title:string body:text status:string
```
fails when tries to create spec in test folder stead of rspec  folder:
```
      invoke  active_record
      create    db/migrate/20210518034404_create_foos.rb
      create    app/models/foo.rb
      invoke    test_unit
/usr/local/lib/ruby/3.0.0/fileutils.rb:253:in `mkdir': Permission denied @ dir_s_mkdir - /app/test (Errno::EACCES)
```

**Comment by ledermann** [comment]
Sorry, the Docker features are targeted for production only. In development mode, the tests are run by:

```bash
bin/rspec
```
