### ISSUE TITLE
Logo Design/Docker-Rails

### ISSUE THREAD

**Issue by baranpirincal** [ledermann/docker-rails#299]
Hey, I examined that your project has no logo design yet. If you interested I can design a logo for Docker-Rails. We can improve it together if you have an idea or want to add/remove something on design. I'm waiting your feedbacks, have a nice day! (it is not advertisement or something, I want to contribute on your project)

Best Regards,
Baran Pirincal
Visual Communication Designer

**Comment by ledermann** [comment]
If you think that this little project needs a logo... ok, why not?
