### ISSUE TITLE
ERROR: No such service: yarn

### ISSUE THREAD

**Issue by ascruggs** [ledermann/docker-rails#324]
Following the "Check it out!" instructions
After having run `docker-compose build` succesfully (assuming a couple webpacker warnings are expected)
`docker-compose run yarn install` outputs
`ERROR: No such service: yarn`

**Comment by ascruggs** [comment]
figured it out. it should be `docker-compose run app yarn install`

**Comment by ledermann** [comment]
You are right, thanks!
