### ISSUE TITLE
bootstrap componets not working

### ISSUE THREAD

**Issue by dutsik** [ledermann/docker-rails#408]
when navigating with turbolinks bootstrap componetns stop working
for instance user dropdown menu or new post tabs.

**Comment by Dutsik** [comment]
I think the issue is with punchbox, when disable it it start working fine

**Comment by ledermann** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [asdasd](https://trello.com/c/D1q2ROI2/1-asdasd)
