### ISSUE TITLE
docker/startup.sh: no such file or directory": unknown

### ISSUE THREAD

**Issue by jay-jlm** [ledermann/docker-rails#705]
Environment:  Docker Toolbox for Windows 10 (Home Edition)
Here is the full log:

> $ docker-compose up
Creating network "dockerrails_default" with the default driver
Creating dockerrails_db_1            ... done
Creating dockerrails_elasticsearch_1 ... done
Creating dockerrails_redis_1         ... done
Creating dockerrails_app_1           ... error

> ERROR: for dockerrails_app_1  Cannot start service app: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"docker/startup.sh\": stat docker/startup.sh: no such file or directory": unknown
> 
> ERROR: for app  Cannot start service app: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"docker/startup.sh\": stat docker/startup.sh: no such file or directory": unknown
> ERROR: Encountered errors while bringing up the project.

**Comment by ledermann** [comment]
Hm, maybe an issue with Windows? Can't reproduce it on Mac or Linux. Perhaps this helps:

In `Dockerfile`, change this:

```
CMD ["docker/startup.sh"]
````

to this:

```
CMD ["/app/docker/startup.sh"]
```

**Comment by Arnie09** [comment]
Hey this issue is still persistent on Windows 11. Any ideas why this is the case? The ruby worker service is running as expected, its just the app service which is exiting.

**Comment by ledermann** [comment]
@Arnie09 Have you tried my suggestion above? Since I don't have Windows here, I can't investigate this further.

**Comment by Arnie09** [comment]
Yes @ledermann I tried that, its giving the same error. I am looking into it.
