### ISSUE TITLE
Some low-effort gems you could add

### ISSUE THREAD

**Issue by MatiasFMolinari** [ledermann/docker-rails#84]
This is a great idea! It's hard to find simple, production-ready implementations of rails tools in the wild. This is quite refreshing.

Have you considered adding these gems: 'searchjoy', 'pghero', 'friendly_id', 'bootsnap',  or 'oj'?

**Comment by ledermann** [comment]
Thanks, I'm glad that this little side project is useful for you. 

This project is some kind of sandbox for me to try out gems or techniques I need for other (real-world) projects or I'm just interested in. It's likely that I will add more gems in the future.
